version: "3.9"

services:
  nfs-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2049:2049"
    image: tholden92/nfs-server
    privileged: true
    volumes:
      - "/exports"
    environment:
      # Creates a user named test and assign groups
      USER_0_NAME: "test"
      USER_0_IDENTIFIER: "1006"
      USER_0_PRIMARY_GROUP_IDENTIFIER: "1007"
      USER_0_SECONDARY_GROUP_IDENTIFIERS: "33"
      USER_0_SECONDARY_GROUP_NAMES: "www-data"
      # Exports a filesystem
      EXPORT_0: "/exports *(rw,insecure,sync,no_subtree_check,fsid=0,no_root_squash)"
      # Spawn 16 worker threads
      THREADS: 16
