name: Build and publish Docker image

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Check out the repo
        uses: actions/checkout@v3

      # Authenticate with docker
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get next version
      - name: Get next version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: patch

      # Install dependencies
      - uses: php-actions/composer@v6

      # Build image
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "tholden92/nfs-server-ubuntu:${{ steps.version.outputs.version }}"
          context: .
